config/routes.rb
Rails.application.routes.draw do
 # devise_for :users

 devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations:'users/registrations'
      }

 
  get "up" => "rails/health#show", as: :rails_health_check

   root 'home#index'

 
  # Defines the root path route ("/")
  # root "posts#index"

  # config/routes.rb
#get "user"=>"admin/user#index"
# namespace :admin do
#   resources :users, only: [:index] # Add this line to define the index route
#   post 'users/:id/block', to: 'users#block', as: :block_user
#   post 'users/:id/unblock', to: 'users#unblock', as: :unblock_user
#   delete 'users/:id/delete', to: 'users#delete', as: :delete_user
# end


  namespace :admin do
    resources :users do
      post :bulk_actions, on: :collection
    end
  end








end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum status: { active: "active", blocked: "blocked", deleted: "deleted" }

  # Method to check if the user is blocked or deleted
  def blocked_or_deleted?
    blocked? || deleted?
  end

  # Method to block the user
  def block!
    update(status: :blocked)
  end

  # Method to unblock the user
  def unblock!
    update(status: :active)
  end

  # Method to delete the user
  def delete!
    update(status: :deleted)
  end

  # Override Devise's active_for_authentication? method to handle blocked or deleted users
  def active_for_authentication?
    super && !blocked_or_deleted?
  end

  # Override Devise's inactive_message method to customize the error message for blocked or deleted users
  def inactive_message
    blocked? ? :blocked : super
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :restrict_to_post_request, only: [:bulk_actions]

  def index
    @users = User.all
  end

  def bulk_actions
    action = params[:button]
    user_ids = params[:user_ids]

    case action
    when 'block'
      User.where(id: user_ids).update_all(status: 'blocked')
      redirect_to admin_users_path, notice: "#{user_ids.count} users blocked successfully"
    when 'unblock'
      User.where(id: user_ids).update_all(status: 'active')
      redirect_to admin_users_path, notice: "#{user_ids.count} users unblocked successfully"
    when 'delete'
      User.where(id: user_ids).destroy_all
      redirect_to admin_users_path, notice: "#{user_ids.count} users deleted successfully"
    else
      redirect_to admin_users_path, alert: 'Invalid action'
    end
  end

  private

  def restrict_to_post_request
    unless request.post?
      redirect_to admin_users_path, alert: 'Invalid request'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      
    end
end
  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    puts "Parameters received in sign up: #{params}"
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:last_sign_in_at])
    puts "Parameters received in sign up: #{params}"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<% if user_signed_in? %>
 
  <div class="card">
    <div class="card-header">
      User Management
    </div>
    <div class="card-body">
      <%= form_with(url: bulk_actions_admin_users_path, id: :bulk_actions_form, method: :post, data: { controller: "form-reset" }) do |form| %>
        <%= form.button type: :submit, value: :block, class: "btn btn-warning" do %>
          <?xml version="1.0" ?><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 6C7 3.23858 9.23858 1 12 1C14.7614 1 17 3.23858 17 6C17 8.76142 14.7614 11 12 11C9.23858 11 7 8.76142 7 6ZM12 3C10.3431 3 9 4.34315 9 6C9 7.65685 10.3431 9 12 9C13.6569 9 15 7.65685 15 6C15 4.34315 13.6569 3 12 3Z" fill="black"/><path d="M4.06189 21C4.55399 17.0537 7.92038 14 12 14C12.8571 14 13.6809 14.1344 14.4525 14.3827L15.4045 14.6889L16.0169 12.785L15.065 12.4787C14.0979 12.1676 13.0675 12 12 12C6.47715 12 2 16.4772 2 22V23H13.6736V21H4.06189Z" fill="black"/><path fill-rule="evenodd" clip-rule="evenodd" d="M15 19C15 16.7909 16.7909 15 19 15C21.2091 15 23 16.7909 23 19C23 21.2091 21.2091 23 19 23C16.7909 23 15 21.2091 15 19ZM19 17C17.8954 17 17 17.8954 17 19C17 19.1792 17.0236 19.3528 17.0677 19.518L19.518 17.0677C19.3528 17.0236 19.1792 17 19 17ZM20.9323 18.482L18.482 20.9323C18.6472 20.9764 18.8208 21 19 21C20.1046 21 21 20.1046 21 19C21 18.8208 20.9764 18.6472 20.9323 18.482Z" fill="black"/></svg>Block
        <% end %>
        <%= form.button type: :submit, value: :unblock, class: "btn btn-primary"  do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"  viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M144 144c0-44.2 35.8-80 80-80c31.9 0 59.4 18.6 72.3 45.7c7.6 16 26.7 22.8 42.6 15.2s22.8-26.7 15.2-42.6C331 33.7 281.5 0 224 0C144.5 0 80 64.5 80 144v48H64c-35.3 0-64 28.7-64 64V448c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V256c0-35.3-28.7-64-64-64H144V144z"/></svg>
         
        <% end %>
        <%= form.button type: :submit, value: :delete, class: "btn btn-danger"  do %>
        <svg xmlns="http://www.w3.org/2000/svg"width="24" height="24" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
          
        <% end %>
        <br>
        <br>
        <table class="table table-light table-hover table-striped">
          <thead class="table-dark">
            <tr>
              <th><input type="checkbox" id="select-all" onclick="toggleAllCheckboxes()"></th>
              <%# <th>ID</th> %>
              <th>Name</th>
              <th>Email</th>
              <th>Last Login Time</th>
              <th>Registration Time</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= check_box_tag "user_ids[]", user.id %></td>
             
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td><%= user.last_sign_in_at %></td>
                <td><%= user.created_at %></td>
                <td><%= user.status %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  // Function to toggle all checkboxes
  function toggleAllCheckboxes() {
    var checkboxes = document.querySelectorAll('input[type="checkbox"][name="user_ids[]"]');
    var selectAllCheckbox = document.getElementById('select-all');

    checkboxes.forEach(function(checkbox) {
      checkbox.checked = selectAllCheckbox.checked;
    });
  }

  // Function to update the select-all checkbox state
  function updateSelectAllCheckbox() {
    var checkboxes = document.querySelectorAll('input[type="checkbox"][name="user_ids[]"]');
    var selectAllCheckbox = document.getElementById('select-all');

    var allChecked = true;
    checkboxes.forEach(function(checkbox) {
      if (!checkbox.checked) {
        allChecked = false;
        return;
      }
    });

    selectAllCheckbox.checked = allChecked;
  }

  // Attach event listener to select-all checkbox
  document.getElementById('select-all').addEventListener('change', function() {
    toggleAllCheckboxes();
  });

  // Attach event listener to individual checkboxes to update select-all checkbox state
  var checkboxes = document.querySelectorAll('input[type="checkbox"][name="user_ids[]"]');
  checkboxes.forEach(function(checkbox) {
    checkbox.addEventListener('change', function() {
      updateSelectAllCheckbox();
    });
  });
</script>

app/views/admin/users/test.html.erb
<div class="card">
  <div class="card-header">
    User Management
  </div>
  <div class="card-body">
    <%= form_tag(admin_users_path, method: :post, id: "bulk-actions-form") do %>
      <table class="table table-light table-hover table-striped">
        <thead class="table-dark">
          <tr>
            <th><input type="checkbox" id="select-all" onclick="toggleAllCheckboxes()"></th>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Last Login Time</th>
            <th>Registration Time</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><input type="checkbox" name="user_ids[]" value="<%= user.id %>"></td>
              <td><%= user.id %></td>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= user.last_sign_in_at %></td>
              <td><%= user.created_at %></td>
              <td><%= user.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="button-group">
        <button type="button" class="btn btn-danger" onclick="bulkAction('block')">Block</button>
        <button type="button" class="btn btn-primary" onclick="bulkAction('unblock')">Unblock</button>
        <button type="button" class="btn btn-warning" onclick="bulkAction('delete')">Delete</button>
      </div>
    <% end %>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script>
  // Function to handle bulk actions
  function bulkAction(action) {
    var form = document.getElementById("bulk-actions-form");
    var actionUrl;

    switch (action) {
      case 'block':
        actionUrl = "/admin/users/bulk_actions/block";
        break;
      case 'unblock':
        actionUrl = "/admin/users/bulk_actions/unblock";
        break;
      case 'delete':
        actionUrl = "/admin/users/bulk_actions/delete";
        break;
    }

    form.action = actionUrl;
    form.submit();
  }

  // Function to toggle all checkboxes based on the header checkbox
  function toggleAllCheckboxes() {
    var checkboxes = document.querySelectorAll("input[name='user_ids[]']");
    var selectAllCheckbox = document.getElementById("select-all");

    checkboxes.forEach(function(checkbox) {
      checkbox.checked = selectAllCheckbox.checked;
    });

    // Set indeterminate state if only some checkboxes are checked
    selectAllCheckbox.indeterminate = checkboxes.length > 0 && !Array.from(checkboxes).every(checkbox => checkbox.checked) && !Array.from(checkboxes).every(checkbox => !checkbox.checked);
  }
</script>

app/views/home/_header.html.erb
<nav class="bg-gray-900">
  <div class="container mx-auto">
    <div class="flex justify-between items-center py-4">
      <div>
        <%= link_to "Friends", root_path , class:"text-white font-bold text-xl"%>
      </div>
      <div class="hidden md:block">
        <ul class="flex space-x-4">
         
          <% if user_signed_in? %>
           <li>
              <%= link_to "User",admin_users_path,class:"text-white hover:text-gray-300" %>
            </li>
            
            <li>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"text-white hover:text-gray-300" %>
            </li>
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path, class:"text-white hover:text-gray-300" %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign in", new_user_session_path, class:"text-white hover:text-gray-300" %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path, class:"text-white hover:text-gray-300" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="md:hidden">
        <button class="text-white focus:outline-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%if current_user %>
 Hii <%=  current_user.username%>

<%else%>

<article class="auto px-8 py-12 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-gradient-to-b from-cyan-500 to-white-500 rounded-md text-white shadow-2xl">
    <h1 class="text-2xl font-bold mb-4">Welcome to <span class="text-2xl">Itransition</span></h1>

    <%= link_to "Sign in", new_user_session_path, class:"btn btn-primary" %>
     <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-info" %>

    

</article>
<%end%>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice%></strong> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "csrf" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </head>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <body>
    <%= render 'home/header'%>  
    <div class="container">
      <%if notice%>
      <%= render 'layouts/alerts'%>
      <%end%>
           
          <p class="alert"><%= alert %></p>
          <%= yield %>
    </div>
     
      
    <%# <main class="container mx-auto mt-28 px-5 flex"> %>
      
    <%# </main> %>
  </body>
</html>